### ISSUE TITLE
Sharing with Redmine Groups doesn't work (OC6)

### ISSUE THREAD

**Issue by jaydio** [ArneMR/user_redmine_ex#1]
Relaying -> https://github.com/owncloud/core/issues/6167 which came up roughly about 5 months ago but still persists. I love your app but IMHO this feature related bug totally defeats its purpose ;)

---

Hi,

Have a redmine authentication plugin installed. In admin, can see the redmine's users and groups.
Have three groups: admin, someredmine, anotherredmine
When trying to share a folder via web interface, admin and someredmine can be found,
anotherredmine is not found.
I.e., (to test) if have three groups, the third one is not "findable" for sharing

Again, sorry if the problem is not in ownCloud.

**Comment by jaydio** [comment]
Hmmm seems like you're no longer working on it. Will just see if I can find some time to dig into it myself and submit a pull request.

**Comment by ArneMR** [comment]
Hi,

I just returned from my holiday yesterday and tried to find the problem. At first I'm no web-developer, developer of Owncloud or what-so-ever. So I also can only guess about the problem.
Up to now I compared the implemented functions with an other user interface implementation. The difference is until now only that the functions "countUsersInGroup" and "displayNamesInGroups" are not implemented in this plugin.
But can you first check in your phpMyAdmin if the SQL rows are working correctly?

**Comment by jaydio** [comment]
Hi Arne, I understand, just wanted to address the issue for you to know what's going on. The rows aren't populated within 'groups' table. At this point I can't afford spending more time on this but one of my developers tries to have a look at it today. We'll commit the changes back once he's got it figured. Since enrolment at our university has started just today all our devs are going to be pretty busy though. Patience.

**Comment by jaydio** [comment]
The issue is indeed with the groups that are not getting populated to the OC database. Due to limitations in time my developers didn't dig further into the owncloud framework to fix this. Now, as the problem was addressed, perhaps you could introduce the necessary changes yourself making it work? :)
